// Deterministic offline backend: builds a tasteful procedural scene from
// the prompt without any model call. Used by tests and when no API key
// is configured. Same prompt -> byte-identical code.
import { mulberry32, hashSeed, r3 } from "../scaffold.mjs";

export const name = "stub";

const PALETTES = [
  { top: 0x2b1055, bottom: 0xff7e5f, ground: 0x140a24, accent: 0x00e5ff },
  { top: 0x0b2a4a, bottom: 0x37c6ff, ground: 0x06121f, accent: 0xffb347 },
  { top: 0x1a1a2e, bottom: 0xe94560, ground: 0x0d0d18, accent: 0x53d8fb },
  { top: 0x0f3d2e, bottom: 0xa8e063, ground: 0x0a1f16, accent: 0xffd166 },
];

const hex = (n) => "0x" + n.toString(16).padStart(6, "0");

function skyBlock(pal) {
  // Sphere with a baked vertical vertex-color gradient.
  const w = 24, h = 16;
  const lines = [];
  lines.push(`const skyGeo = new THREE.SphereGeometry(40, ${w}, ${h});`);
  lines.push(`{`);
  lines.push(`  const pos = skyGeo.attributes.position;`);
  lines.push(`  const colors = new Float32Array(pos.count * 3);`);
  lines.push(`  const top = new THREE.Color(${hex(pal.top)});`);
  lines.push(`  const bottom = new THREE.Color(${hex(pal.bottom)});`);
  lines.push(`  const c = new THREE.Color();`);
  lines.push(`  for (let i = 0; i < pos.count; i++) {`);
  lines.push(`    const t = THREE.MathUtils.clamp(pos.getY(i) / 40, -1, 1) * 0.5 + 0.5;`);
  lines.push(`    c.copy(bottom).lerp(top, t);`);
  lines.push(`    colors[i * 3] = c.r; colors[i * 3 + 1] = c.g; colors[i * 3 + 2] = c.b;`);
  lines.push(`  }`);
  lines.push(`  skyGeo.setAttribute('color', new THREE.BufferAttribute(colors, 3));`);
  lines.push(`}`);
  lines.push(`scene.add(new THREE.Mesh(skyGeo, new THREE.MeshBasicMaterial({ side: THREE.BackSide, vertexColors: true, fog: false })));`);
  return lines.join("\n");
}

function boxesBlock(pal, count) {
  const lines = [];
  lines.push(`const boxes = new THREE.InstancedMesh(`);
  lines.push(`  new THREE.BoxGeometry(1, 1, 1),`);
  lines.push(`  new THREE.MeshStandardMaterial({ roughness: 0.35, metalness: 0.55 }),`);
  lines.push(`  ${count});`);
  lines.push(`{`);
  lines.push(`  const m = new THREE.Matrix4();`);
  lines.push(`  const q = new THREE.Quaternion();`);
  lines.push(`  const e = new THREE.Euler();`);
  lines.push(`  const v = new THREE.Vector3();`);
  lines.push(`  const s = new THREE.Vector3();`);
  lines.push(`  const col = new THREE.Color();`);
  lines.push(`  const accent = new THREE.Color(${hex(pal.accent)});`);
  lines.push(`  const base = new THREE.Color(0x8a93a6);`);
  lines.push(`  const spots = [`);
  // Bake deterministic transforms so the module itself has no RNG.
  const r2 = mulberry32(hashSeed("boxes-spots") ^ count);
  const spots = [];
  for (let i = 0; i < count; i++) {
    const x = r3((r2() - 0.5) * 14);
    const y = r3(0.5 + r2() * 3.5);
    const z = r3((r2() - 0.5) * 8 - 2);
    const sx = r3(0.5 + r2() * 1.6), sy = r3(0.5 + r2() * 1.6), sz = r3(0.5 + r2() * 1.6);
    const rx = r3(r2() * Math.PI), ry = r3(r2() * Math.PI), rz = 0;
    const mix = r3(r2());
    spots.push(`    [${x}, ${y}, ${z}, ${sx}, ${sy}, ${sz}, ${rx}, ${ry}, ${rz}, ${mix}]`);
  }
  lines.push(spots.join(",\n"));
  lines.push(`  ];`);
  lines.push(`  spots.forEach((p, i) => {`);
  lines.push(`    e.set(p[6], p[7], p[8]); q.setFromEuler(e);`);
  lines.push(`    v.set(p[0], p[1], p[2]); s.set(p[3], p[4], p[5]);`);
  lines.push(`    m.compose(v, q, s); boxes.setMatrixAt(i, m);`);
  lines.push(`    col.copy(base).lerp(accent, p[9] * 0.55); boxes.setColorAt(i, col);`);
  lines.push(`  });`);
  lines.push(`  boxes.instanceMatrix.needsUpdate = true;`);
  lines.push(`  if (boxes.instanceColor) boxes.instanceColor.needsUpdate = true;`);
  lines.push(`}`);
  lines.push(`scene.add(boxes);`);
  return lines.join("\n");
}

/**
 * Generate a deterministic scene module from the request.
 * Returns { code }.
 */
export async function generateSceneCode({ prompt, placement = "hero", style = "", budget = "medium" }) {
  const seed = hashSeed(`${placement}|${budget}|${style}|${prompt}`);
  const rng = mulberry32(seed);
  const pal = PALETTES[Math.floor(rng() * PALETTES.length)];
  const count = budget === "low" ? 8 : budget === "high" ? 28 : 16;

  const cam = placement === "product"
    ? `camera.position.set(0, 2.6, 7.5);\ncamera.lookAt(0, 1.4, 0);`
    : placement === "background"
      ? `camera.position.set(0, 0, 9);\ncamera.lookAt(0, 1.5, 0);`
      : `camera.position.set(-4.5, 1.8, 10.5);\ncamera.lookAt(2.5, 1.2, 0);`;

  const code = `import * as THREE from 'three';

// Generated by render-3d (stub backend) — deterministic offline scene.
// Prompt: ${String(prompt ?? "").replace(/[\r\n\u2028\u2029]/g, " ").slice(0, 160)}

export const scene = new THREE.Scene();
scene.fog = new THREE.Fog(${hex(pal.ground)}, 14, 34);

${skyBlock(pal)}

// Ground
{
  const ground = new THREE.Mesh(
    new THREE.CircleGeometry(30, 48),
    new THREE.MeshStandardMaterial({ color: ${hex(pal.ground)}, roughness: 0.95, metalness: 0 })
  );
  ground.rotation.x = -Math.PI / 2;
  ground.position.y = -0.6;
  scene.add(ground);
}

${boxesBlock(pal, count)}

// Accent torus
{
  const torus = new THREE.Mesh(
    new THREE.TorusGeometry(1.6, 0.22, 24, 72),
    new THREE.MeshStandardMaterial({ color: ${hex(pal.accent)}, roughness: 0.25, metalness: 0.8, emissive: ${hex(pal.accent)}, emissiveIntensity: 0.25 })
  );
  torus.position.set(${r3(2 + rng() * 2)}, ${r3(2.5 + rng() * 1.5)}, -3);
  torus.rotation.set(${r3(rng() * 0.6)}, ${r3(rng() * 1.2)}, 0);
  scene.add(torus);
}

scene.add(new THREE.HemisphereLight(0xcfd8ff, ${hex(pal.ground)}, 0.85));
const key = new THREE.DirectionalLight(0xfff1dd, 2.0);
key.position.set(5, 8, 6);
scene.add(key);
const rim = new THREE.DirectionalLight(${hex(pal.accent)}, 0.9);
rim.position.set(-6, 4, -5);
scene.add(rim);

export const camera = new THREE.PerspectiveCamera(50, 1280 / 800, 0.1, 120);
${cam}
`;
  return { code };
}
